[package]
name = "dungeon-generation-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25"
imageproc = "0.25"
env_logger = "0.11"
log = "0.4"
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
rand = "0.9"

[lints.rust]
dead_code = "allow"